# Load and explore the data

## Import libraries

In [24]:
# Import pandas, numpy, and matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# seaborn is a data visualization library built on matplotlib
import seaborn as sns

# set the plotting style
sns.set_style("whitegrid")

## Load the data

##### Load the Seattle data set

In [25]:
df = pd.read_csv('seattle_rain.csv')
df_seattle = df.head()

##### Load the St. Louis data set

In [26]:
df = pd.read_csv('stl_rain.csv')
df_stl = df.head()

## Explore the contents of the data sets

##### Start by looking at the head of each data frame.

This will let us see the names of the columns and a few example values for each column.

##### Examine more rows

##### St. Louis data set

In [27]:
df_stl

,STATION,NAME,DATE,DAPR,MDPR,PRCP,SNOW,SNWD
0,US1MOSS0027,"ST. CHARLES 2.3 NE, MO US",2017-01-01,NaN,NaN,0.00,0.0,NaN
1,US1MOSS0027,"ST. CHARLES 2.3 NE, MO US",2017-01-03,NaN,NaN,0.35,NaN,NaN
2,US1MOSS0027,"ST. CHARLES 2.3 NE, MO US",2017-01-04,NaN,NaN,0.03,NaN,NaN
3,US1MOSS0027,"ST. CHARLES 2.3 NE, MO US",2017-01-05,NaN,NaN,0.04,1.2,NaN
4,US1MOSS0027,"ST. CHARLES 2.3 NE, MO US",2017-01-06,NaN,NaN,0.00,0.0,1.0

##### Are the columns are the same?

##### Use the `info` method to check the data types, size of the data frame, and numbers of missing values.

##### St. Louis data set

##### We can also compare data frame sizes using the shape attribute

## Why might the St. Louis data set be larger?

<pre>































</pre>

#### Examine the `STATION` column

##### How many unique stations are present?

#### Examine the `DATE` column

### Be careful to use correct data types

### Convert `DATE` to datetime

### What range of dates are present?

### Are the data suitable for answering the question?

Plot the daily precipitation data for Seattle.

##### Plot the daily precipitation data for St. Louis.

## Tutorial: Selecting subsets of a DataFrame

In [23]:
df_seattle.head()

,STATION,NAME,DATE,DAPR,MDPR,PRCP,SNOW,SNWD,WESD,WESF
0,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/1/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
1,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/2/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/3/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
3,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/4/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
4,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/5/18,NaN,NaN,0.25,NaN,NaN,NaN,NaN

### Select one column

Select the column containing precipitation `PRCP`.

#### Use dictionary-style indexing

#### Use explicit array-style indexing with loc

#### Use implicit array-style indexing with `.iloc`

What number column, starting with 0, is `PRCP`?

In [ ]:
df_seattle.head()

##### Use implicit array-style indexing with `.iloc`

### Select multiple columns

Select the columns containing `STATION`, `DATE`, and precipitation `PRCP`.

##### Use .loc

##### Use .iloc

#### Select a range of columns

Select all columns from `STATION` through `PRCP`

##### Use .iloc

### Select the first $n$ rows

Select the first 3 rows

Use the `.head()` method

##### Use explicit indexing

##### Use implicit indexing

### Select the last $n$ rows

Use the `.tail()` method

##### Use explicit indexing

##### Use implicit indexing

### Select rows using logical indexing

Select the rows where `PRCP` is greater than 0.

##### Select the rows where the precipitation is between 0.5 and 0.75 inches.

## Select relevant subsets of the data

We saw that the St. Louis data set contains data prior to 2018.

##### Limit the St. Louis data to 2018 and beyond.

In [ ]:
df_stlouis = df_stlouis.loc(df_stlouis[‘DATE’] >= ‘2018-01-01’]

In [ ]:
df_stlouis.head()

##### The St. Louis data set has values for many weather stations, while the Seattle data set has only one weather station.

We will focus on the data from the airport in St. Louis.

## Join data frames keeping `DATE` and `PRCP` columns

In [ ]:
df_stlouis = df_stlouis.loc(df_stlouis['NAME'] == 'ST LOUIS LAMBERT INTERNATIONAL AIRPORT, MO US']

In [ ]:
df_stlouis['STATION'].unique()

**What type of join should we do?**

##### Use a join to keep all dates present

Each DataFrame had a column named `PRCP`, so the default is to add suffixes _x and _y to differentiate the columns. Normally, I would rename the columns at this point to something more informative. However, I know that I want to convert the DataFrame to a tidy format and I will modify the names later.

### Create a tidy data frame with columns for city and precipitation

In [ ]:
df = df_stlouis[['DATE','PRECP'].merge(df_seattle[['DATE','PRECP']], on='DATE', how= 'outer')

How did this change the DataFrame?

In [ ]:
df.head()

### Rename columns or values to follow best practices

Rename the city values 'STL' and 'SEA'

##### Rename the columns to be lowercase using `df.rename()`

In [ ]:
df = pd.melt(df, idvars='DATE', var_name='city', value_name='precipitation')

## Identify and fill in missing values

Data can be missing in multiple manners:
1. Values are `NaN` in the data frame

2.  Values are not included in the data set.

### Count the non-null or null values

In [ ]:
df.nota().sum()

Determine the number of non-null values in each column.

In [ ]:
df.isna().sum()

##### Determine the number of null values in each column.

##### Determine the number of null precipitation values for Seattle and St. Louis.

##### The St. Louis data set does not have any `NaN` values of `precipitation`. Are any dates omitted?

**How many data points should we have from 2018 to 2022?**

### Impute missing values

We will replace missing values with the mean across years of values on that day.


**Design an algorithm for replacing missing values with the mean across years of values on that day.**

In [ ]:
df['day_of_year'] = pd.DateTimeIndex(df['date'']). day_of_year
    df.head()

In [ ]:
calc the man value of precipitation

mean_day_precipitaiton=df.loc[

## Export the clean .csv file

In [ ]:
df.to_csv('clean_seattle_stlouis_weather.csv', encoding='utf-8-sig', index=False)